[tox]
envlist = update-sources,build
skipsdist = true

[testenv]
passenv =
    STREAM
    REGISTRY
    NAMESPACE
    TAG
    IMAGE_PREFIX
    BASE_IMAGE
    CONSTRAINTS_FILE
    DEFAULT_STREAM
    REGISTRY_AUTH_FILE
    PARALLEL
    BUILD_LOGS_DIR
deps =
    pip-tools
allowlist_externals =
    bash

[testenv:update-sources]
commands =
    bash {toxinidir}/build.sh update-sources all

[testenv:build]
commands =
    bash {toxinidir}/build.sh build all

[testenv:custom]
commands =
    bash {toxinidir}/build.sh {posargs}
